### ISSUE TITLE
Can't find the inception_v2.ckpt

### ISSUE THREAD

**Issue by PumayHui** [SMH17/TensorBoxPy3#2]
@SMH17 Hello, I can't find the 'inception_v2.ckpt', can you give me some advices? Thank you
so much!

**Comment by SMH17** [comment]
You can get inception_v2.ckpt training Inception v2 with an image set according your needs. Otherwise you can get the model pretrained on ILSVRC-2012-CLS dataset using `download_sample_data` script.

**Comment by PumayHui** [comment]
Thank you so much! @SMH17
