### ISSUE TITLE
stitch_rects ImportError: DLL load failed

### ISSUE THREAD

**Issue by PumayHui** [SMH17/TensorBoxPy3#3]
@SMH17 
Hello, when I run evaluate.py, it occured such an error：
`from .stitch_wrapper import stitch_rects
ImportError: DLL load failed`
So I rebuild the stitch_wrapper.pyx by `python setup.py build_ext --inplace` , 'setup.py' like this:
`from distutils.core import setup
from Cython.Build import cythonize
setup(
    ext_modules = cythonize("stitch_wrapper.pyx")
)`
Then it has make stitch_wrapper.c, but no stitch_wrapper.pyd, and occured such mistakes:
`C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\cstdint(18): error C2054: expected '(' to follow 'using'`

What should I do?
Thank you!

**Comment by SMH17** [comment]
You have to use `cmake `correctly to build stitch_wrapper on Windows
https://cmake.org/
